#!/bin/bash

cp /home/jocala/android/kernel.ancora_tmo.ics/fs/cifs/cifs.ko .
cp /home/jocala/android/kernel.ancora_tmo.ics/drivers/bluetooth/bthid/bthid.ko .
cp /home/jocala/android/kernel.ancora_tmo.ics/drivers/net/wireless/bcm4329/dhd.ko .
cp /home/jocala/android/kernel.ancora_tmo.ics/drivers/param/sec_param.ko .
cp /home/jocala/android/kernel.ancora_tmo.ics/arch/arm/boot/zImage .

