#!/bin/sh

cp /home/jocala/build/kernels/samsung.ancora.ics/fs/cifs/cifs.ko .
cp /home/jocala/build/kernels/samsung.ancora.ics/fs/cifs/slow-work.ko .
cp /home/jocala/build/kernels/samsung.ancora.ics/drivers/bluetooth/bthid/bthid.ko .
cp /home/jocala/build/kernels/samsung.ancora.ics/drivers/net/wireless/bcm4329/dhd.ko .
cp /home/jocala/build/kernels/samsung.ancora.ics/drivers/param/sec_param.ko .
cp /home/jocala/build/kernels/samsung.ancora.ics/arch/arm/boot/zImage ./kernel





